### ISSUE TITLE
ParseError: Expected =

### ISSUE THREAD

**Issue by yhoiseth** [evidence-dev/evidence#103]
I have a fairly complicated query that results in the following error message (both in the terminal and in the browser).

```
500
Expected =
38:             a.id,
39:             tr.id,
40:             concat(extract(year FROM tr. "vestedDate"), '-', extract(quarter FROM tr. "vestedDate")) AS vesteddate,
                                                              ^
41:             t.name,
42:             a.employee_id,
ParseError: Expected =
    at error (file:///Users/yngve/Repositories/evidence/my-project/node_modules/svelte/compiler.mjs:17650:19)
    at Parser$1.error (file:///Users/yngve/Repositories/evidence/my-project/node_modules/svelte/compiler.mjs:17726:9)
    at read_attribute (file:///Users/yngve/Repositories/evidence/my-project/node_modules/svelte/compiler.mjs:16976:16)
    at tag (file:///Users/yngve/Repositories/evidence/my-project/node_modules/svelte/compiler.mjs:16827:25)
    at new Parser$1 (file:///Users/yngve/Repositories/evidence/my-project/node_modules/svelte/compiler.mjs:17685:21)
    at parse$3 (file:///Users/yngve/Repositories/evidence/my-project/node_modules/svelte/compiler.mjs:17817:20)
    at compile (file:///Users/yngve/Repositories/evidence/my-project/node_modules/svelte/compiler.mjs:31091:17)
    at compileSvelte (file:///Users/yngve/Repositories/evidence/my-project/node_modules/@sveltejs/kit/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:301:20)
    at async TransformContext.transform (file:///Users/yngve/Repositories/evidence/my-project/node_modules/@sveltejs/kit/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:1325:27)
    at async Object.transform (/Users/yngve/Repositories/evidence/my-project/node_modules/vite/dist/node/chunks/dep-f2b4ca46.js:50923:30)
```

This same query is running fine in TablePlus against the same database. It also runs fine in Google Data Studio. (I’m not comfortable sharing the query publicly, but I can share it privately. Considering that it may be useless without the accompanying database, I’d also be happy to do a debugging session.)

I have tried replacing the offending line with `'2021-1' AS vesteddate,`. That leaves me with a similar error:

```
500
Expected =
38:             a.id,
39:             tr.id,
40:             '2021-1' AS vesteddate,
                       ^
41:             t.name,
42:             a.employee_id,
ParseError: Expected =
    at error (file:///Users/yngve/Repositories/evidence/my-project/node_modules/svelte/compiler.mjs:17650:19)
    at Parser$1.error (file:///Users/yngve/Repositories/evidence/my-project/node_modules/svelte/compiler.mjs:17726:9)
    at read_attribute (file:///Users/yngve/Repositories/evidence/my-project/node_modules/svelte/compiler.mjs:16976:16)
    at tag (file:///Users/yngve/Repositories/evidence/my-project/node_modules/svelte/compiler.mjs:16827:25)
    at new Parser$1 (file:///Users/yngve/Repositories/evidence/my-project/node_modules/svelte/compiler.mjs:17685:21)
    at parse$3 (file:///Users/yngve/Repositories/evidence/my-project/node_modules/svelte/compiler.mjs:17817:20)
    at compile (file:///Users/yngve/Repositories/evidence/my-project/node_modules/svelte/compiler.mjs:31091:17)
    at compileSvelte (file:///Users/yngve/Repositories/evidence/my-project/node_modules/@sveltejs/kit/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:301:20)
    at async TransformContext.transform (file:///Users/yngve/Repositories/evidence/my-project/node_modules/@sveltejs/kit/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:1325:27)
    at async Object.transform (/Users/yngve/Repositories/evidence/my-project/node_modules/vite/dist/node/chunks/dep-f2b4ca46.js:50923:30)
```

**Comment by hughess** [comment]
Thanks - the single quotes issue is now our highest priority and we're hoping to have a fix for that soon. We hadn't originally anticipated the impact it would have on postgres users. Will keep you posted on it!
