### ISSUE TITLE
Why only one datasource?

### ISSUE THREAD

**Issue by andrejohansson** [evidence-dev/evidence#1123]
## Request Type

- [ ] Small Fix (wording, errors, typos, etc.)
- [X] Explanation Improvement (make a description clearer for the reader of the docs)
- [ ] Walkthrough Request (new tutorial for a particular feature or use case)
- [ ] Other

## Description

In the section regarding [datasources](https://docs.evidence.dev/core-concepts/data-sources/) I see no mention about the limitation to only having one datasource per project. There is a note about it on the settings page.

Why is an Evidence project limited to one datasource? It´s quite a big limitation. Being able to bring together reports together from multiple data sources seems to me to be one of the biggest points of any BI tool. What am I missing?

## If improving on existing content, where is that content located?

https://docs.evidence.dev/core-concepts/data-sources/

**Comment by mcrascal** [comment]
Hi @andrejohansson, really just for simplicities sake when we were getting started with the project, but we are working on support for multiple data sources.  

Most BI tools which offer great support for multiple data sources include their own query engine in addition to connections to other databases, so that you can combine data across multiple sources. The current version of Evidence doesn't have this, but that's what we're building here (powered by duckdb): #768 

You can try the pre-release of this version of Evidence here: https://github.com/evidence-dev/template/tree/next

Closing for now!

**Comment by andrejohansson** [comment]
Thank you for the answer and pointer!

**Comment by andrejohansson** [comment]
@mcrascal I tried the instructions you told me, but I get an internal server error and the following error message:

```


[plugin:vite:import-analysis] Missing "./fonts.css" specifier in "@evidence-dev/tailwind" package

D:/lab/evidence-multiple/.evidence/template/src/pages/+layout.svelte

Error: Missing "./fonts.css" specifier in "@evidence-dev/tailwind" package
    at e (file:///D:/lab/evidence-multiple/node_modules/vite/dist/node/chunks/dep-df561101.js:21420:25)
    at n (file:///D:/lab/evidence-multiple/node_modules/vite/dist/node/chunks/dep-df561101.js:21420:627)
    at o (file:///D:/lab/evidence-multiple/node_modules/vite/dist/node/chunks/dep-df561101.js:21420:1297)
    at resolveExportsOrImports (file:///D:/lab/evidence-multiple/node_modules/vite/dist/node/chunks/dep-df561101.js:28712:20)
    at resolveDeepImport (file:///D:/lab/evidence-multiple/node_modules/vite/dist/node/chunks/dep-df561101.js:28731:31)
    at tryNodeResolve (file:///D:/lab/evidence-multiple/node_modules/vite/dist/node/chunks/dep-df561101.js:28419:20)
    at Context.resolveId (file:///D:/lab/evidence-multiple/node_modules/vite/dist/node/chunks/dep-df561101.js:28180:28)
    at Object.resolveId (file:///D:/lab/evidence-multiple/node_modules/vite/dist/node/chunks/dep-df561101.js:44207:64)
    at async TransformContext.resolve (file:///D:/lab/evidence-multiple/node_modules/vite/dist/node/chunks/dep-df561101.js:43923:23)
    at async normalizeUrl (file:///D:/lab/evidence-multiple/node_modules/vite/dist/node/chunks/dep-df561101.js:41793:34

Click outside, press Esc key, or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.js.

```

Could [this MR](https://github.com/evidence-dev/evidence/pull/1083/files#diff-fa1a09a730c2e023d801b0e75fc6ab3f56ac47f73d223c70e364ca454fd4e261) be the cause?

**Comment by mcrascal** [comment]
@ItsMeBrianD thoughts? @andrejohansson we also have a slack channel for the prerelease if you're keen.

**Comment by ItsMeBrianD** [comment]
I think this is due to an issue we had with changesets; it should be fixable by adding this to your package.json:

```json
{
  "overrides": {
    "@evidence-dev/tailwind": "1.0.0-usql.1"
  }
}
```

Then run `npm i` and try to run it again
