### ISSUE TITLE
Vite SSR Errors

### ISSUE THREAD

**Issue by hughess** [evidence-dev/evidence#121]
Several users are seeing errors from Vite related to SSR. These issues are detailed here: sveltejs/kit#2086. One example is vitejs/vite#3953.

There should be a workaround until those are fixed by using older package versions, which work for running an Evidence project. Specific versions to be added to docs.

**Comment by mrshu** [comment]
Hi @hughess ,

I just tried to boot up `evidence` and ended up running into the following:

```
23:27:36 [vite-plugin-svelte] /Users/mrshu/work/mrshu/my-proje/node_modules/@evidence-dev/components/ui/LoadingIndicator.svelte:42:1 Unused CSS selector ":global(html).dark .fade"
23:27:38 [vite] Error when evaluating SSR module /node_modules/@evidence-dev/db-orchestrator/index.cjs:
ReferenceError: require is not defined
    at /node_modules/@evidence-dev/db-orchestrator/index.cjs:1:95
    at instantiateModule (/Users/mrshu/work/mrshu/my-proje/node_modules/@sveltejs/kit/node_modules/vite/dist/node/chunks/dep-713b45e1.js:66472:15)
Line must be greater than or equal to 1, got -1
TypeError: Line must be greater than or equal to 1, got -1
    at BasicSourceMapConsumer.SourceMapConsumer_findMapping [as _findMapping] (/Users/mrshu/work/mrshu/my-proje/node_modules/@sveltejs/kit/node_modules/vite/dist/node/chunks/dep-713b45e1.js:65336:13)
    at BasicSourceMapConsumer.SourceMapConsumer_originalPositionFor [as originalPositionFor] (/Users/mrshu/work/mrshu/my-proje/node_modules/@sveltejs/kit/node_modules/vite/dist/node/chunks/dep-713b45e1.js:65405:22)
    at /Users/mrshu/work/mrshu/my-proje/node_modules/@sveltejs/kit/node_modules/vite/dist/node/chunks/dep-713b45e1.js:66344:34
    at String.replace (<anonymous>)
    at /Users/mrshu/work/mrshu/my-proje/node_modules/@sveltejs/kit/node_modules/vite/dist/node/chunks/dep-713b45e1.js:66334:21
    at Array.map (<anonymous>)
    at ssrRewriteStacktrace (/Users/mrshu/work/mrshu/my-proje/node_modules/@sveltejs/kit/node_modules/vite/dist/node/chunks/dep-713b45e1.js:66333:10)
    at instantiateModule (/Users/mrshu/work/mrshu/my-proje/node_modules/@sveltejs/kit/node_modules/vite/dist/node/chunks/dep-713b45e1.js:66475:28)
Unexpected token T in JSON at position 0
SyntaxError: Unexpected token T in JSON at position 0
    at JSON.parse (<anonymous>)
    at Proxy.<anonymous> (file:///Users/mrshu/work/mrshu/my-proje/node_modules/@sveltejs/kit/dist/ssr.js:839:22)
    at async load (/Users/mrshu/work/mrshu/my-proje/src/pages/firstquery.md:32:19)
    at async load_node (file:///Users/mrshu/work/mrshu/my-proje/node_modules/@sveltejs/kit/dist/ssr.js:867:12)
    at async respond$1 (file:///Users/mrshu/work/mrshu/my-proje/node_modules/@sveltejs/kit/dist/ssr.js:1118:15)
    at async render_page (file:///Users/mrshu/work/mrshu/my-proje/node_modules/@sveltejs/kit/dist/ssr.js:1272:20)
    at async resolve (file:///Users/mrshu/work/mrshu/my-proje/node_modules/@sveltejs/kit/dist/ssr.js:1617:10)
    at async respond (file:///Users/mrshu/work/mrshu/my-proje/node_modules/@sveltejs/kit/dist/ssr.js:1592:10)
    at async Immediate.<anonymous> (file:///Users/mrshu/work/mrshu/my-proje/node_modules/@sveltejs/kit/dist/chunks/index.js:3458:22)
23:27:39 [vite-plugin-svelte] /Users/mrshu/work/mrshu/my-proje/node_modules/@evidence-dev/components/ui/LoadingIndicator.svelte:42:1 Unused CSS selector ":global(html).dark .fade"
```

Would you say it's the same thing? is there anything I can do to fix it?

Thanks a bunch!

**Comment by hughess** [comment]
@mrshu good news - we've just released a fixed version, so you should be able to get started with it! Let me know if you run into any issues and I can help out. Thanks a ton for your patience on this!
