### ISSUE TITLE
URL params for filtering break build process

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#1256]
## Steps To Reproduce

[Thread in Slack](https://evidencedev.slack.com/archives/C023LRB9Z40/p1697124217738069)

1. Create a project with the following markdown
2. `npm run build:strict`

```markdown
# Welcome to Evidence

{#if $page.url.searchParams.get('myParam')}
  
{$page.url.searchParams.get('myParam')}

{:else}

My param does not exist

{/if}
```

### Environment

- Node version (`node -v`): Node.js v20.6.1
- npm version (`npm -v`):
- OS: MacOS Ventura
- Browser: Firefox
- Database: duckdb
- Evidence:
@evidence-dev/core-components@2.0.3
@evidence-dev/evidence@22.0.0

## Expected Behavior

Build succeeds and the url param is accessible on the page

## Actual Behaviour

Build fails

```
node:internal/event_target:1083
  process.nextTick(() => { throw err; });
                           ^
Error: 500 /
To suppress or handle this error, implement `handleHttpError` in https://kit.svelte.dev/docs/configuration#prerender
    at file:///Users/archie/Projects/template/node_modules/@sveltejs/kit/src/core/config/options.js:212:13
    at file:///Users/archie/Projects/template/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:64:25
    at save (file:///Users/archie/Projects/template/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:403:4)
    at visit (file:///Users/archie/Projects/template/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:236:3)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:326:10)
    at [kOnMessage] (node:internal/worker:337:37)
    at MessagePort.<anonymous> (node:internal/worker:232:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:807:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)

Node.js v20.6.1
Build failed

file:///Users/archie/Projects/template/node_modules/@evidence-dev/evidence/cli.js:152
                        throw `Build process exited with code ${code}`;
                        ^
Build process exited with code 1
(Use `node --trace-uncaught ...` to show where the exception was thrown)
```

## Workarounds

Anything you can do in advance of this being fixed?

**Comment by archiewood** [comment]
closed by #1257
