### ISSUE TITLE
Basic Getstart not working. Getting: `window is not defined`

### ISSUE THREAD

**Issue by nehiljain** [evidence-dev/evidence#1524]
## Steps To Reproduce

I did the standard setup. https://docs.evidence.dev/getting-started/install-evidence
I tried both with and without dbt.

### Environment

- Node version (`node -v`): v21.5.0
- npm version (`npm -v`): 10.2.4
- OS: macOS Sonoma 14.2.1 (23C71)
- Browser: chrome, safari
- Database: duckdb

## Expected Behavior

Expected to load the app in my browser

## Actual Behaviour

Error:

```
Internal server error: window is not defined
      at detect (/Users/nehiljain/code/future-dynamics/future_dynamics_transformations/reports/node_modules/echarts/dist/echarts.js:123:54)
      at /Users/nehiljain/code/future-dynamics/future_dynamics_transformations/reports/node_modules/echarts/dist/echarts.js:97:9
      at /Users/nehiljain/code/future-dynamics/future_dynamics_transformations/reports/node_modules/echarts/dist/echarts.js:22:68
      at Object.<anonymous> (/Users/nehiljain/code/future-dynamics/future_dynamics_transformations/reports/node_modules/echarts/dist/echarts.js:25:2)
      at Module._compile (node:internal/modules/cjs/loader:1375:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1434:10)
      at Module.load (node:internal/modules/cjs/loader:1206:32)
      at Module._load (node:internal/modules/cjs/loader:1022:12)
      at cjsLoader (node:internal/modules/esm/translators:358:17)
      at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:307:7) (x5)
```

Describe what happened. Error messages and screenshots are helpful.

**Comment by hughess** [comment]
Hi @nehiljain! This is caused by your NodeJS version - Evidence requires version 18 or 20. Let me know if you need any help getting one of those versions set up

**Comment by nehiljain** [comment]
That worked. Thanks @hughess
