### ISSUE TITLE
ReferenceError [Error]: window is not defined

### ISSUE THREAD

**Issue by creativedutchmen** [evidence-dev/evidence#1633]
## Steps To Reproduce

Follow the steps in the docs:

```
npx degit evidence-dev/template my-project
cd my-project
npm install
npm run sources
npm run dev
```

### Environment

- Node version (`node -v`): v21.6.2 (homebrew)
- npm version (`npm -v`): 10.4.0 (homebrew)
- OS: 14.1 (23B74)
- Browser: not applicable
- Database: not applicable

## Expected Behavior

Should be able to start the dev server from the minimal example - works in docker

## Actual Behaviour

The build fails with the following error:
```
ReferenceError [Error]: window is not defined
    at detect (/Users/huib/Projects/jedlix/evidence/node_modules/echarts/dist/echarts.js:123:54)
    at /Users/huib/Projects/jedlix/evidence/node_modules/echarts/dist/echarts.js:97:9
    at /Users/huib/Projects/jedlix/evidence/node_modules/echarts/dist/echarts.js:22:68
    at Object.<anonymous> (/Users/huib/Projects/jedlix/evidence/node_modules/echarts/dist/echarts.js:25:2)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at cjsLoader (node:internal/modules/esm/translators:359:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:308:7)
```

## Workarounds

No workaround found (except using Docker)

**Comment by hughess** [comment]
@creativedutchmen Node v21 is not supported - you can use v20 or v18. 

Let me know if you need any help setting up a different node version
