### ISSUE TITLE
Templated pages fail to build when generated from query with date input

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#2029]
## Steps To Reproduce

Builds with templated pages fail when templated pages generated from query containing date input

https://github.com/davidgasquez/templated-pages-test/tree/repro-prerendered-issue

```bash
npm run sources
npm run build
```

### Environment

- Node version (`node -v`): 20
- npm version (`npm -v`):
- OS: macos
- Browser: 
- Database: duckdb

## Expected Behavior

Build completes

## Actual Behaviour

Build fails at final stage

```
✓ built in 19.99s

node:internal/event_target:1083
  process.nextTick(() => { throw err; });
                           ^
Error: The following routes were marked as prerenderable, but were not prerendered because they were not found while crawling your app:
  - /orders/[order]

See https://kit.svelte.dev/docs/page-options#prerender-troubleshooting for info on how to solve this
    at prerender (file:///Users/archie/Projects/templated-pages-test/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:495:9)
    at async MessagePort.<anonymous> (file:///Users/archie/Projects/templated-pages-test/node_modules/@sveltejs/kit/src/utils/fork.js:22:16)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:326:10)
    at [kOnMessage] (node:internal/worker:337:37)
    at MessagePort.<anonymous> (node:internal/worker:232:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:807:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)

Node.js v20.6.1
Build failed

file:///Users/archie/Projects/templated-pages-test/node_modules/@evidence-dev/evidence/cli.js:178
                        throw `Build process exited with code ${code}`;
                        ^
Build process exited with code 1
(Use `node --trace-uncaught ...` to show where the exception was thrown)

Node.js v20.6.1
```

## Workarounds

Anything you can do in advance of this being fixed?

**Comment by hilkeheremans** [comment]
workaround: 
- use a non-filtered version of the query
- populate a datatable with links based on that query, but put it inside a `<div class="hidden">`

svelte will then pick up the pages for rendering
