### ISSUE TITLE
Hello world example breaks locally

### ISSUE THREAD

**Issue by koaning** [evidence-dev/evidence#2040]
## Steps To Reproduce

I ran the hello world tutorial locally. The `npm run dev` command ran perfectly fine, but the `npm run build` command gave some errors. Here's the log: 

```
my-project ✗ npm run build

> my-evidence-project@0.0.1 build
> evidence build

vite v5.2.10 building SSR bundle for production...
✓ 1367 modules transformed.
vite v5.2.10 building for production...
✓ 4025 modules transformed.
.svelte-kit/output/client/_app/version.json                                                                 0.03 kB │ gzip:     0.05 kB
.svelte-kit/output/client/_app/immutable/assets/wordmark-gray-800.CnzB_64T.png                             11.87 kB
.svelte-kit/output/client/.vite/manifest.json                                                              33.57 kB │ gzip:     3.19 kB
.svelte-kit/output/client/_app/immutable/assets/Spectral-ExtraLight.HPQmpGpQ.woff2                         55.57 kB
.svelte-kit/output/client/_app/immutable/assets/Spectral-ExtraLightItalic.xW7ezc0a.woff2                   58.00 kB
.svelte-kit/output/client/_app/immutable/assets/Spectral-Regular.BE1HJwUh.woff2                            58.09 kB
.svelte-kit/output/client/_app/immutable/assets/Spectral-Italic.wSPWDyg7.woff2                             58.78 kB
.svelte-kit/output/client/_app/immutable/assets/Spectral-Light.TIhg4DnI.woff2                              58.91 kB
.svelte-kit/output/client/_app/immutable/assets/Spectral-ExtraBold.DeRaT2m-.woff2                          59.18 kB
.svelte-kit/output/client/_app/immutable/assets/Spectral-ExtraBoldItalic.MQ9B1Gco.woff2                    59.74 kB
.svelte-kit/output/client/_app/immutable/assets/Spectral-LightItalic.zW0f9iJS.woff2                        60.67 kB
.svelte-kit/output/client/_app/immutable/assets/Spectral-SemiBold.zu1TM2FZ.woff2                           60.88 kB
.svelte-kit/output/client/_app/immutable/assets/Spectral-Medium.NsGaEaui.woff2                             61.13 kB
.svelte-kit/output/client/_app/immutable/assets/Spectral-Bold.BwJz_A1v.woff2                               61.29 kB
.svelte-kit/output/client/_app/immutable/assets/Spectral-MediumItalic.BvSK_s7Y.woff2                       61.88 kB
.svelte-kit/output/client/_app/immutable/assets/Spectral-SemiBoldItalic.D3fgUf4W.woff2                     62.13 kB
.svelte-kit/output/client/_app/immutable/assets/Spectral-BoldItalic.CQC_WCFZ.woff2                         62.16 kB
.svelte-kit/output/client/_app/immutable/assets/Spectral-ExtraLight.HAWHIZWB.woff                          69.52 kB
.svelte-kit/output/client/_app/immutable/assets/Spectral-Regular.C0aqGnDS.woff                             72.05 kB
.svelte-kit/output/client/_app/immutable/assets/Spectral-ExtraLightItalic.C9nFbxmj.woff                    72.68 kB
.svelte-kit/output/client/_app/immutable/assets/Spectral-Light.DBct1VnS.woff                               72.94 kB
.svelte-kit/output/client/_app/immutable/assets/Spectral-ExtraBold.Dm6k0JyR.woff                           73.01 kB
.svelte-kit/output/client/_app/immutable/assets/Spectral-Italic.3s0_PsVL.woff                              73.28 kB
.svelte-kit/output/client/_app/immutable/assets/Spectral-ExtraBoldItalic.SZr5i_vZ.woff                     74.36 kB
.svelte-kit/output/client/_app/immutable/assets/Spectral-SemiBold.CCUIByHq.woff                            75.12 kB
.svelte-kit/output/client/_app/immutable/assets/Spectral-LightItalic.B3o_X74d.woff                         75.20 kB
.svelte-kit/output/client/_app/immutable/assets/Spectral-Medium.BZl4fq6u.woff                              75.20 kB
.svelte-kit/output/client/_app/immutable/assets/Spectral-Bold.C57huwyI.woff                                75.81 kB
.svelte-kit/output/client/_app/immutable/assets/Spectral-MediumItalic.De40Wj9n.woff                        76.62 kB
.svelte-kit/output/client/_app/immutable/assets/Spectral-SemiBoldItalic.DjbDqXej.woff                      76.77 kB
.svelte-kit/output/client/_app/immutable/assets/Spectral-BoldItalic.CQquRzSI.woff                          76.91 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-Regular.CKDp9E3C.woff2                               98.87 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-Thin.CSJ_owlW.woff2                                  99.63 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-Black.DgUKMdlB.woff2                                102.87 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-ExtraLight.egkqWonf.woff2                           104.23 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-Light.CdXm_ABL.woff2                                104.33 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-SemiBold.Ctx7G98q.woff2                             105.80 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-Medium.P1cOs5ep.woff2                               105.92 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-ExtraBold.B0QOs-T2.woff2                            106.11 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-Bold.CuhepTt8.woff2                                 106.14 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-ThinItalic.B6FKq6qK.woff2                           106.50 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-Italic._3PMmu0i.woff2                               106.88 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-BlackItalic.ZFcDzO3e.woff2                          108.75 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-LightItalic.COmGGTuG.woff2                          111.33 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-ExtraLightItalic.Bf25KIHs.woff2                     111.39 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-ExtraBoldItalic.OErwaGem.woff2                      111.71 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-BoldItalic.R15IsAnq.woff2                           111.81 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-SemiBoldItalic.BNz1Al2H.woff2                       112.05 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-MediumItalic.DWiIAHvp.woff2                         112.18 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-Regular.DJOZHnwz.woff                               133.84 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-Thin.CVMZtQER.woff                                  135.92 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-Black.DtxVgCT8.woff                                 138.76 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-Light.CG9upfZ4.woff                                 140.63 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-ExtraLight.CbFdmbHh.woff                            140.72 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-Medium.oHczPpWt.woff                                142.55 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-ExtraBold.B8imQN9B.woff                             142.92 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-SemiBold.BHlX_6qk.woff                              142.93 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-Bold.2PT7Q-hu.woff                                  143.21 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-Italic.Ci_5KQU1.woff                                144.37 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-ThinItalic.B2bFwwDp.woff                            145.48 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-BlackItalic.CkZ-ktDH.woff                           146.82 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-ExtraLightItalic.B3gY-m5W.woff                      150.00 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-LightItalic.C2ZuFZOC.woff                           150.09 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-ExtraBoldItalic.Bt8eprh6.woff                       150.63 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-MediumItalic.8laNK8GF.woff                          150.99 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-BoldItalic.C906RMVC.woff                            151.05 kB
.svelte-kit/output/client/_app/immutable/assets/Inter-SemiBoldItalic.CxeAX7g8.woff                        151.18 kB
.svelte-kit/output/client/_app/immutable/workers/duckdb-browser-eh.worker-DT-uzeza.js                     262.80 kB
.svelte-kit/output/client/_app/immutable/workers/duckdb-browser-mvp.worker-DgEo6Ag5.js                    315.60 kB
.svelte-kit/output/client/_app/immutable/assets/duckdb-eh.Bbw6HAmJ.wasm                                18,105.92 kB
.svelte-kit/output/client/_app/immutable/assets/duckdb-mvp.IKz61icS.wasm                               22,092.38 kB
.svelte-kit/output/client/_app/immutable/assets/0.DVTwT-_f.css                                             57.96 kB │ gzip:    10.85 kB
.svelte-kit/output/client/_app/immutable/assets/VennDiagram.DV8QANWb.css                                   74.92 kB │ gzip:    16.76 kB
.svelte-kit/output/client/_app/immutable/chunks/index.R8ovVqwX.js                                           0.03 kB │ gzip:     0.05 kB
.svelte-kit/output/client/_app/immutable/chunks/profile.BW8tN6E9.js                                         0.06 kB │ gzip:     0.08 kB
.svelte-kit/output/client/_app/immutable/entry/start.D54vdjnk.js                                            0.07 kB │ gzip:     0.08 kB
.svelte-kit/output/client/_app/immutable/chunks/globalContexts.1hDlTDmj.js                                  0.07 kB │ gzip:     0.08 kB
.svelte-kit/output/client/_app/immutable/chunks/duckdb-eh.CFvZubNE.js                                       0.10 kB │ gzip:     0.12 kB
.svelte-kit/output/client/_app/immutable/chunks/duckdb-mvp.CbpRbetm.js                                      0.10 kB │ gzip:     0.12 kB
.svelte-kit/output/client/_app/immutable/chunks/duckdb-browser-eh.worker.Cbrkkz2F.js                        0.17 kB │ gzip:     0.16 kB
.svelte-kit/output/client/_app/immutable/chunks/duckdb-browser-mvp.worker.Bw9aQXtH.js                       0.17 kB │ gzip:     0.16 kB
.svelte-kit/output/client/_app/immutable/nodes/2.CDRE9wPq.js                                                0.27 kB │ gzip:     0.23 kB
.svelte-kit/output/client/_app/immutable/chunks/stores.B9npXy64.js                                          0.29 kB │ gzip:     0.18 kB
.svelte-kit/output/client/_app/immutable/nodes/3.CMEY96FR.js                                                0.60 kB │ gzip:     0.39 kB
.svelte-kit/output/client/_app/immutable/chunks/preload-helper.D6kgxu3v.js                                  1.06 kB │ gzip:     0.63 kB
.svelte-kit/output/client/_app/immutable/chunks/index.Cw3VsyJa.js                                           1.96 kB │ gzip:     0.80 kB
.svelte-kit/output/client/_app/immutable/chunks/index.BUqOVkrY.js                                           3.10 kB │ gzip:     1.08 kB
.svelte-kit/output/client/_app/immutable/chunks/Button.BAscxaM2.js                                          3.26 kB │ gzip:     1.50 kB
.svelte-kit/output/client/_app/immutable/chunks/CopyIcon.77ut-EEJ.js                                        5.01 kB │ gzip:     2.36 kB
.svelte-kit/output/client/_app/immutable/nodes/4.BDdDZ5U1.js                                                5.19 kB │ gzip:     2.05 kB
.svelte-kit/output/client/_app/immutable/chunks/Prismjs.LxFFQJFJ.js                                         5.27 kB │ gzip:     2.94 kB
.svelte-kit/output/client/_app/immutable/chunks/index.HcpD0Qi0.js                                           5.73 kB │ gzip:     2.81 kB
.svelte-kit/output/client/_app/immutable/chunks/button.B4vN2jnr.js                                          6.67 kB │ gzip:     2.62 kB
.svelte-kit/output/client/_app/immutable/nodes/1.CtSHgIeO.js                                                7.08 kB │ gzip:     2.73 kB
.svelte-kit/output/client/_app/immutable/entry/app.zwGlzn7J.js                                              8.67 kB │ gzip:     2.84 kB
.svelte-kit/output/client/_app/immutable/nodes/6.BWKy--Rg.js                                               10.70 kB │ gzip:     3.82 kB
.svelte-kit/output/client/_app/immutable/chunks/scheduler.DAj4RI7w.js                                      11.19 kB │ gzip:     4.44 kB
.svelte-kit/output/client/_app/immutable/chunks/index.ta-mt3DI.js                                          15.32 kB │ gzip:     2.34 kB
.svelte-kit/output/client/_app/immutable/chunks/AccordionItem.DTYhb1FL.js                                  20.52 kB │ gzip:     5.10 kB
.svelte-kit/output/client/_app/immutable/chunks/utils.C8IhOsGN.js                                          21.53 kB │ gzip:     7.28 kB
.svelte-kit/output/client/_app/immutable/chunks/colours.DqV0zGfB.js                                        27.16 kB │ gzip:     9.23 kB
.svelte-kit/output/client/_app/immutable/chunks/entry.DYFUtxpb.js                                          28.81 kB │ gzip:    11.34 kB
.svelte-kit/output/client/_app/immutable/nodes/5.yqUa35Uu.js                                              124.61 kB │ gzip:    34.81 kB
.svelte-kit/output/client/_app/immutable/nodes/7.eoJBJD0t.js                                              170.43 kB │ gzip:    49.69 kB
.svelte-kit/output/client/_app/immutable/nodes/8.ByvIL2-3.js                                              179.31 kB │ gzip:    52.86 kB
.svelte-kit/output/client/_app/immutable/nodes/0.j76WGOGq.js                                              215.58 kB │ gzip:    57.02 kB
.svelte-kit/output/client/_app/immutable/chunks/index.DNh9dtbm.js                                         269.24 kB │ gzip:    68.73 kB
.svelte-kit/output/client/_app/immutable/chunks/VennDiagram.svelte_svelte_type_style_lang.BjKvemjc.js   1,861.57 kB │ gzip:   616.06 kB
.svelte-kit/output/client/_app/immutable/chunks/index.CGB6X0u6.js                                       4,918.07 kB │ gzip: 1,899.99 kB

(!) Some chunks are larger than 500 kB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ built in 21.23s

node:internal/event_target:1062
  process.nextTick(() => { throw err; });
                           ^
Error: 404 /new/settings (linked from /new/)
To suppress or handle this error, implement `handleHttpError` in https://kit.svelte.dev/docs/configuration#prerender
    at file:///Users/vincent/Development/calmcode.io/my-project/my-project/node_modules/@sveltejs/kit/src/core/config/options.js:202:13
    at file:///Users/vincent/Development/calmcode.io/my-project/my-project/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:65:25
    at save (file:///Users/vincent/Development/calmcode.io/my-project/my-project/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:403:4)
    at visit (file:///Users/vincent/Development/calmcode.io/my-project/my-project/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:236:3)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:314:10)
    at [kOnMessage] (node:internal/worker:325:37)
    at MessagePort.<anonymous> (node:internal/worker:225:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:786:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)

Node.js v18.19.0
Build failed

file:///Users/vincent/Development/calmcode.io/my-project/my-project/node_modules/@evidence-dev/evidence/cli.js:178
                        throw `Build process exited with code ${code}`;
                        ^
Build process exited with code 1
(Use `node --trace-uncaught ...` to show where the exception was thrown)

Node.js v18.19.0
```

I am more of a Python dev myself, so I am not sure how to debug this, but it felt like something that shouldn't break either way.

### Environment

- Node version (`node -v`): 18.19.0
- npm version (`npm -v`): 10.2.3
- OS: MacOS
- Browser: -
- Database: -

## Expected Behavior

I expect the build to work on the hello world quickstart.

## Actual Behaviour

Logs above show details.

## Workarounds

Not really.

**Comment by archiewood** [comment]
I cannot reproduce this. 

This 404 error occurs during build when there is a link to a non-existent page from another page. It's a safeguard so your site does not have dead links in production

`Error: 404 /new/settings (linked from /new/)` suggests you have a page called `new.md` in your `/pages` directory, and it has a link to a page called `/new/settings` from it, but you have not created a `/new/settings.md` page

**Comment by koaning** [comment]
Ah, my bad! You're right. But my changes are relatively minimal.

The 'new.md' file contains the original index.md file and the original index.md file now contains this:

```
---
title: Welcome to Evidence
---

There are a bunch of pages here. This is one:

- [/new](new)
```

These changes do feel relatively minimal that it is still suprising to see it fail like this.
