### ISSUE TITLE
[Bug]: ENOENT: no such file or directory, open '[app]/.evidence/template/src/pages/settings/+page.md'

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/evidence#2571]
### Describe the bug

launch a new project from VSCode, get an error printed to the terminal

```
Uncaught error while server responding {
  error: Error: ENOENT: no such file or directory, open '/Users/archie/test-ch/.evidence/template/src/pages/settings/+page.md'
      at async open (node:internal/fs/promises:639:25)
      at async Object.readFile (node:internal/fs/promises:1249:14)
      at async GET (/Users/archie/test-ch/.evidence/template/src/pages/api/[...route]/evidencemeta.json/+server.js:38:18)
      at async Module.render_endpoint (/Users/archie/test-ch/node_modules/@sveltejs/kit/src/runtime/server/endpoint.js:43:18)
      at async resolve (/Users/archie/test-ch/node_modules/@sveltejs/kit/src/runtime/server/respond.js:443:17)
      at async Module.respond (/Users/archie/test-ch/node_modules/@sveltejs/kit/src/runtime/server/respond.js:319:20)
      at async file:///Users/archie/test-ch/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:524:22 {
    errno: -2,
    code: 'ENOENT',
    syscall: 'open',
    path: '/Users/archie/test-ch/.evidence/template/src/pages/settings/+page.md'
```

### Steps to Reproduce

launch a new project from VSCode, 

### Severity

serious, but I can work around it

**Comment by kwongz** [comment]
Getting similar errors when launching latest template

Uncaught error while server responding {
  error: [Error: ENOENT: no such file or directory, open 'C:\Users\Kylew.DESKTOP-Q3QTV5P.000\test-broken\.evidence\template\src\pages\settings\+page.md'] {
    errno: -4058,
    code: 'ENOENT',
    syscall: 'open',
    path: 'C:\\Users\\Kylew.DESKTOP-Q3QTV5P.000\\test-broken\\.evidence\\template\\src\\pages\\settings\\+page.md'

**Comment by archiewood** [comment]
@ItsMeBrianD thinks this is an extraneous console log
