### ISSUE TITLE
[Bug]: The following routes were marked as prerenderable /manifest.webmanifest

### ISSUE THREAD

**Issue by spinscale** [evidence-dev/evidence#2820]
### Describe the bug

I cannot run `npm run build` due to an error with `/manifest.webmanifest` like this

```
(!) Some chunks are larger than 500 kB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
✓ built in 16.13s

node:internal/event_target:1090
  process.nextTick(() => { throw err; });
                           ^
Error: The following routes were marked as prerenderable, but were not prerendered because they were not found while crawling your app:
  - /manifest.webmanifest

See https://kit.svelte.dev/docs/page-options#prerender-troubleshooting for info on how to solve this
    at prerender (file:///Users/alr/devel/alphaess/evidence/node_modules/@sveltejs/kit/src/core/postbuild/prerender.js:495:9)
    at async MessagePort.<anonymous> (file:///Users/alr/devel/alphaess/evidence/node_modules/@sveltejs/kit/src/utils/fork.js:22:16)

Node.js v22.11.0

Build failed

file:///Users/alr/devel/alphaess/evidence/node_modules/@evidence-dev/evidence/cli.js:190
                        throw `Build process exited with code ${code}`;
                        ^
Build process exited with code 1
(Use `node --trace-uncaught ...` to show where the exception was thrown)

Node.js v22.11.0
```

### Steps to Reproduce

I am not sure, what I can help to reproduce, my node/evidence skills are too limited to decide what could be the cause of this. If you need anything, please ping me.

### Logs

```Shell

```

### System Info

```Shell
System:
    OS: macOS 15.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 3.50 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.11.0 - ~/.local/state/fnm_multishells/26218_1732055397470/bin/node
    Yarn: 1.22.22 - /opt/homebrew/bin/yarn
    npm: 10.9.0 - ~/.local/state/fnm_multishells/26218_1732055397470/bin/npm
  Browsers:
    Brave Browser: 119.1.60.118
    Chrome: 130.0.6723.92
    Edge: 119.0.2151.72
    Safari: 18.1
  npmPackages:
    @evidence-dev/bigquery: ^2.0.8 => 2.0.8
    @evidence-dev/core-components: ^4.8.3 => 4.8.13
    @evidence-dev/csv: ^1.0.12 => 1.0.13
    @evidence-dev/databricks: ^1.0.7 => 1.0.7
    @evidence-dev/duckdb: ^1.0.11 => 1.0.12
    @evidence-dev/evidence: ^39.1.10 => 39.1.17
    @evidence-dev/motherduck: ^1.0.2 => 1.0.3
    @evidence-dev/mssql: ^1.0.10 => 1.1.1
    @evidence-dev/mysql: ^1.1.3 => 1.1.3
    @evidence-dev/postgres: ^1.0.6 => 1.0.6
    @evidence-dev/snowflake: ^1.1.2 => 1.2.1
    @evidence-dev/sqlite: ^2.0.6 => 2.0.6
    @evidence-dev/trino: ^1.0.8 => 1.0.8
```

### Severity

annoyance

**Comment by archiewood** [comment]
try deleting `.evidence`

then redo 

npm run sources
npm run build

**Comment by spinscale** [comment]
That was it. Thank you so much!
